org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8 -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses=true
kotlin.daemon.jvmargs=-Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configureondemand=true
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
android.useFullNativeAlignment=true
android.experimental.androidTest.useUnifiedTestPlatform=false
    
# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
