package com.lop.budget.domain.model

// GÉNÉRÉ PAR scripts/GenerateCurrencyCatalog.java — NE PAS ÉDITER À LA MAIN.
//
// Devises en usage dans au moins un pays ISO, nom et symbole résolus pour la locale
// française — la même que celle qui formate les montants (Format.money).
// Ordre d'affichage figé ici (P-3) : un filtre de recherche le conserve sans le retrier.
internal val CURRENCY_CATALOG: List<AppCurrency> = listOf(
    AppCurrency("EUR", "Euro", "€", "EU"),
    AppCurrency("USD", "Dollar des États-Unis", "\$US", "US"),
    AppCurrency("GBP", "Livre sterling", "£GB", "GB"),
    AppCurrency("CHF", "Franc suisse", "CHF", "CH"),
    AppCurrency("CAD", "Dollar canadien", "\$CA", "CA"),
    AppCurrency("JPY", "Yen japonais", "JPY", "JP"),
    AppCurrency("XOF", "Franc CFA (BCEAO)", "F CFA", null),
    AppCurrency("MAD", "Dirham marocain", "MAD", "MA"),
    AppCurrency("AED", "Dirham des Émirats arabes unis", "AED", "AE"),
    AppCurrency("AFN", "Afghani afghan", "AFN", "AF"),
    AppCurrency("ALL", "Lek albanais", "ALL", "AL"),
    AppCurrency("AMD", "Dram arménien", "AMD", "AM"),
    AppCurrency("ANG", "Florin antillais", "ANG", null),
    AppCurrency("AOA", "Kwanza angolais", "AOA", "AO"),
    AppCurrency("ARS", "Peso argentin", "\$AR", "AR"),
    AppCurrency("AUD", "Dollar australien", "\$AU", "AU"),
    AppCurrency("AWG", "Florin arubais", "AWG", "AW"),
    AppCurrency("AZN", "Manat azéri", "AZN", "AZ"),
    AppCurrency("BAM", "Mark convertible bosniaque", "BAM", "BA"),
    AppCurrency("BBD", "Dollar barbadien", "BBD", "BB"),
    AppCurrency("BDT", "Taka bangladeshi", "BDT", "BD"),
    AppCurrency("BGN", "Lev bulgare", "BGN", "BG"),
    AppCurrency("BHD", "Dinar bahreïni", "BHD", "BH"),
    AppCurrency("BIF", "Franc burundais", "BIF", "BI"),
    AppCurrency("BMD", "Dollar bermudien", "\$BM", "BM"),
    AppCurrency("BND", "Dollar brunéien", "\$BN", "BN"),
    AppCurrency("BOB", "Boliviano bolivien", "BOB", "BO"),
    AppCurrency("BRL", "Réal brésilien", "R\$", "BR"),
    AppCurrency("BSD", "Dollar bahaméen", "BSD", "BS"),
    AppCurrency("BTN", "Ngultrum bouthanais", "BTN", "BT"),
    AppCurrency("BWP", "Pula botswanais", "BWP", "BW"),
    AppCurrency("BYN", "Rouble biélorusse", "BYN", "BY"),
    AppCurrency("BZD", "Dollar bélizéen", "\$BZ", "BZ"),
    AppCurrency("CDF", "Franc congolais", "CDF", "CD"),
    AppCurrency("CLP", "Peso chilien", "\$CL", "CL"),
    AppCurrency("CNY", "Yuan renminbi chinois", "CNY", "CN"),
    AppCurrency("COP", "Peso colombien", "\$CO", "CO"),
    AppCurrency("CRC", "Colón costaricain", "CRC", "CR"),
    AppCurrency("CUP", "Peso cubain", "CUP", "CU"),
    AppCurrency("CVE", "Escudo capverdien", "CVE", "CV"),
    AppCurrency("CZK", "Couronne tchèque", "CZK", "CZ"),
    AppCurrency("DJF", "Franc djiboutien", "DJF", "DJ"),
    AppCurrency("DKK", "Couronne danoise", "DKK", "DK"),
    AppCurrency("DOP", "Peso dominicain", "DOP", "DO"),
    AppCurrency("DZD", "Dinar algérien", "DZD", "DZ"),
    AppCurrency("EGP", "Livre égyptienne", "EGP", "EG"),
    AppCurrency("ERN", "Nafka érythréen", "ERN", "ER"),
    AppCurrency("ETB", "Birr éthiopien", "ETB", "ET"),
    AppCurrency("FJD", "Dollar fidjien", "\$FJ", "FJ"),
    AppCurrency("FKP", "Livre des îles Malouines", "£FK", "FK"),
    AppCurrency("GEL", "Lari géorgien", "GEL", "GE"),
    AppCurrency("GHS", "Cédi ghanéen", "GHS", "GH"),
    AppCurrency("GIP", "Livre de Gibraltar", "£GI", "GI"),
    AppCurrency("GMD", "Dalasi gambien", "GMD", "GM"),
    AppCurrency("GNF", "Franc guinéen", "GNF", "GN"),
    AppCurrency("GTQ", "Quetzal guatémaltèque", "GTQ", "GT"),
    AppCurrency("GYD", "Dollar du Guyana", "GYD", "GY"),
    AppCurrency("HKD", "Dollar de Hong Kong", "HKD", "HK"),
    AppCurrency("HNL", "Lempira hondurien", "HNL", "HN"),
    AppCurrency("HTG", "Gourde haïtienne", "HTG", "HT"),
    AppCurrency("HUF", "Forint hongrois", "HUF", "HU"),
    AppCurrency("IDR", "Roupie indonésienne", "IDR", "ID"),
    AppCurrency("ILS", "Nouveau shekel israélien", "₪", "IL"),
    AppCurrency("INR", "Roupie indienne", "₹", "IN"),
    AppCurrency("IQD", "Dinar irakien", "IQD", "IQ"),
    AppCurrency("IRR", "Riyal iranien", "IRR", "IR"),
    AppCurrency("ISK", "Couronne islandaise", "ISK", "IS"),
    AppCurrency("JMD", "Dollar jamaïcain", "JMD", "JM"),
    AppCurrency("JOD", "Dinar jordanien", "JOD", "JO"),
    AppCurrency("KES", "Shilling kényan", "KES", "KE"),
    AppCurrency("KGS", "Som kirghize", "KGS", "KG"),
    AppCurrency("KHR", "Riel cambodgien", "KHR", "KH"),
    AppCurrency("KMF", "Franc comorien", "KMF", "KM"),
    AppCurrency("KPW", "Won nord-coréen", "KPW", "KP"),
    AppCurrency("KRW", "Won sud-coréen", "₩", "KR"),
    AppCurrency("KWD", "Dinar koweïtien", "KWD", "KW"),
    AppCurrency("KYD", "Dollar des îles Caïmans", "KYD", "KY"),
    AppCurrency("KZT", "Tenge kazakh", "KZT", "KZ"),
    AppCurrency("LAK", "Kip laotien", "LAK", "LA"),
    AppCurrency("LBP", "Livre libanaise", "£LB", "LB"),
    AppCurrency("LKR", "Roupie srilankaise", "LKR", "LK"),
    AppCurrency("LRD", "Dollar libérien", "LRD", "LR"),
    AppCurrency("LSL", "Loti lesothan", "LSL", "LS"),
    AppCurrency("LYD", "Dinar libyen", "LYD", "LY"),
    AppCurrency("MDL", "Leu moldave", "MDL", "MD"),
    AppCurrency("MGA", "Ariary malgache", "MGA", "MG"),
    AppCurrency("MKD", "Denar macédonien", "MKD", "MK"),
    AppCurrency("MMK", "Kyat myanmarais", "MMK", "MM"),
    AppCurrency("MNT", "Tugrik mongol", "MNT", "MN"),
    AppCurrency("MOP", "Pataca macanaise", "MOP", "MO"),
    AppCurrency("MRU", "Ouguiya mauritanien", "MRU", "MR"),
    AppCurrency("MUR", "Roupie mauricienne", "MUR", "MU"),
    AppCurrency("MVR", "Rufiyaa maldivien", "MVR", "MV"),
    AppCurrency("MWK", "Kwacha malawite", "MWK", "MW"),
    AppCurrency("MXN", "Peso mexicain", "\$MX", "MX"),
    AppCurrency("MYR", "Ringgit malais", "MYR", "MY"),
    AppCurrency("MZN", "Metical mozambicain", "MZN", "MZ"),
    AppCurrency("NAD", "Dollar namibien", "\$NA", "NA"),
    AppCurrency("NGN", "Naira nigérian", "NGN", "NG"),
    AppCurrency("NIO", "Córdoba oro nicaraguayen", "NIO", "NI"),
    AppCurrency("NOK", "Couronne norvégienne", "NOK", "NO"),
    AppCurrency("NPR", "Roupie népalaise", "NPR", "NP"),
    AppCurrency("NZD", "Dollar néo-zélandais", "\$NZ", "NZ"),
    AppCurrency("OMR", "Riyal omanais", "OMR", "OM"),
    AppCurrency("PAB", "Balboa panaméen", "PAB", "PA"),
    AppCurrency("PEN", "Sol péruvien", "PEN", "PE"),
    AppCurrency("PGK", "Kina papouan-néo-guinéen", "PGK", "PG"),
    AppCurrency("PHP", "Peso philippin", "PHP", "PH"),
    AppCurrency("PKR", "Roupie pakistanaise", "PKR", "PK"),
    AppCurrency("PLN", "Zloty polonais", "PLN", "PL"),
    AppCurrency("PYG", "Guaraní paraguayen", "PYG", "PY"),
    AppCurrency("QAR", "Riyal qatari", "QAR", "QA"),
    AppCurrency("RON", "Leu roumain", "RON", "RO"),
    AppCurrency("RSD", "Dinar serbe", "RSD", "RS"),
    AppCurrency("RUB", "Rouble russe", "RUB", "RU"),
    AppCurrency("RWF", "Franc rwandais", "RWF", "RW"),
    AppCurrency("SAR", "Riyal saoudien", "SAR", "SA"),
    AppCurrency("SBD", "Dollar des îles Salomon", "\$SB", "SB"),
    AppCurrency("SCR", "Roupie des Seychelles", "SCR", "SC"),
    AppCurrency("SDG", "Livre soudanaise", "SDG", "SD"),
    AppCurrency("SEK", "Couronne suédoise", "SEK", "SE"),
    AppCurrency("SGD", "Dollar de Singapour", "\$SG", "SG"),
    AppCurrency("SHP", "Livre de Sainte-Hélène", "SHP", "SH"),
    AppCurrency("SLE", "Sierra Leonean Leone", "SLE", "SL"),
    AppCurrency("SOS", "Shilling somalien", "SOS", "SO"),
    AppCurrency("SRD", "Dollar surinamais", "\$SR", "SR"),
    AppCurrency("SSP", "Livre sud-soudanaise", "SSP", "SS"),
    AppCurrency("STN", "Dobra santoméen", "STN", "ST"),
    AppCurrency("SVC", "Colón salvadorien", "SVC", "SV"),
    AppCurrency("SYP", "Livre syrienne", "SYP", "SY"),
    AppCurrency("SZL", "Lilangeni swazi", "SZL", "SZ"),
    AppCurrency("THB", "Baht thaïlandais", "THB", "TH"),
    AppCurrency("TJS", "Somoni tadjik", "TJS", "TJ"),
    AppCurrency("TMT", "Nouveau manat turkmène", "TMT", "TM"),
    AppCurrency("TND", "Dinar tunisien", "TND", "TN"),
    AppCurrency("TOP", "Pa’anga tongan", "TOP", "TO"),
    AppCurrency("TRY", "Livre turque", "TRY", "TR"),
    AppCurrency("TTD", "Dollar de Trinité-et-Tobago", "\$TT", "TT"),
    AppCurrency("TWD", "Nouveau dollar taïwanais", "TWD", "TW"),
    AppCurrency("TZS", "Shilling tanzanien", "TZS", "TZ"),
    AppCurrency("UAH", "Hryvnia ukrainienne", "UAH", "UA"),
    AppCurrency("UGX", "Shilling ougandais", "UGX", "UG"),
    AppCurrency("UYU", "Peso uruguayen", "\$UY", "UY"),
    AppCurrency("UZS", "Sum ouzbek", "UZS", "UZ"),
    AppCurrency("VES", "Bolivar vénézuélien", "VES", "VE"),
    AppCurrency("VND", "Dông vietnamien", "₫", "VN"),
    AppCurrency("VUV", "Vatu vanuatuan", "VUV", "VU"),
    AppCurrency("WST", "Tala samoan", "\$WS", "WS"),
    AppCurrency("XAF", "Franc CFA (BEAC)", "FCFA", null),
    AppCurrency("XCD", "Dollar des Caraïbes orientales", "XCD", null),
    AppCurrency("XPF", "Franc CFP", "FCFP", null),
    AppCurrency("YER", "Riyal yéménite", "YER", "YE"),
    AppCurrency("ZAR", "Rand sud-africain", "ZAR", "ZA"),
    AppCurrency("ZMW", "Kwacha zambien", "ZMW", "ZM"),
    AppCurrency("ZWL", "Dollar zimbabwéen (2009)", "ZWL", "ZW"),
)
