# config.yaml
name: "LOPBudget - API 36 (FR)"
device-os: "android-36"       # Format attendu par Maestro (ex: android-34, android-36)
device-locale: "fr_FR"        # Force la langue de l'appareil
includeTags: "smoke"