# config.yaml
name: "LOPBudget - Validation Suppression & Historique" # Nom affiché sur le dashboard
appId: "com.lop.budget"

# Appareils cibles sur le Cloud
device:
  - "model=Pixel 7,os=13"
  - "model=Galaxy S24 Ultra,os=14"


# Variables d'environnement pour les scripts Maestro
env:
  - "ENV=staging"
  - "DEBUG_MODE=true"